package in.ecomexpress.sruti.ui.base;

import android.annotation.TargetApi;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.drawable.ColorDrawable;
import android.location.Location;
import android.location.LocationManager;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.util.Log;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.view.inputmethod.InputMethodManager;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.LayoutRes;
import androidx.annotation.Nullable;
import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.app.AppCompatDelegate;
import androidx.core.content.ContextCompat;
import androidx.databinding.DataBindingUtil;
import androidx.databinding.ViewDataBinding;
import androidx.lifecycle.Observer;

import com.google.android.gms.maps.model.LatLng;
import com.google.android.material.snackbar.Snackbar;
import com.google.firebase.analytics.FirebaseAnalytics;
import com.google.maps.android.SphericalUtil;

import java.util.ArrayList;

import javax.inject.Inject;

import dagger.android.AndroidInjection;
import in.ecomexpress.sruti.R;
import in.ecomexpress.sruti.SrutiApplication;
import in.ecomexpress.sruti.databinding.ActivityMultiSpaceBinding;
import in.ecomexpress.sruti.databinding.WarningDialogBinding;
import in.ecomexpress.sruti.model.DeviceDetails;
import in.ecomexpress.sruti.repo.IDataManager;
import in.ecomexpress.sruti.utils.CommonUtils;
import in.ecomexpress.sruti.utils.common_files.NetworkUtils;

/**
 * Generated by Dipendra 08/11/17 - 05:46 PM
 *
 * @param <T> the type parameter
 * @param <V> the type parameter
 */
public abstract class BaseActivity<T extends ViewDataBinding, V extends BaseViewModel>
        extends AppCompatActivity implements BaseFragment.Callback {

    private ProgressDialog mProgressDialog;
    private T mViewDataBinding;
    private V mViewModel;
    @Inject
    public DeviceDetails deviceDetails;
    private String fe_distanceFromSeller;

    public String getFe_distanceFromSeller() {
        return fe_distanceFromSeller;
    }

    public void setFe_distanceFromSeller(String fe_distanceFromSeller) {
        this.fe_distanceFromSeller = fe_distanceFromSeller;
    }

    private AlertDialog gpsAlertBuilder;
    private boolean isGPSDialogVisible = false;

    private FirebaseAnalytics mFirebaseAnalytics;
    private long startTime;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        performDependencyInjection();
        performDataBinding();
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
        gpsAlertBuilder = new AlertDialog.Builder(this)
                .setTitle("GPS Disabled !!")
                .setMessage("Please enable GPS to further use the application.")
                .setCancelable(false)
                .setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                    public void onClick(final DialogInterface dialog, final int id) {
                        isGPSDialogVisible = false;
                        dialog.dismiss();
                        startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS));
                    }
                }).create();


        mViewModel.isGPSEnabled.observe(this, new Observer<Boolean>() {
            @Override
            public void onChanged(Boolean aBoolean) {
                if (aBoolean) {
                    if (gpsAlertBuilder != null && isGPSDialogVisible) {
                        isGPSDialogVisible = false;
                        gpsAlertBuilder.dismiss();
                    }
                } else {
                    if (!isGPSDialogVisible) {
                        gpsAlertBuilder.show();
                        isGPSDialogVisible = true;
                    }
                }

            }
        });
        mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);


    }
    public FirebaseAnalytics getFirebaseAnalytics() {
        return mFirebaseAnalytics;
    }


    private void performDataBinding() {
        mViewDataBinding = DataBindingUtil.setContentView(this, getLayoutId());
        this.mViewModel = mViewModel == null ? getViewModel() : mViewModel;
        mViewDataBinding.setVariable(getBindingVariable(), mViewModel);
        mViewDataBinding.executePendingBindings();
    }


    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(newBase);
    }

    /**
     * Request permissions safely.
     *
     * @param permissions the permissions
     * @param requestCode the request code
     */
    @TargetApi(Build.VERSION_CODES.M)
    public void requestPermissionsSafely(String[] permissions, int requestCode) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            requestPermissions(permissions, requestCode);
        }
    }


    /**
     * Has permission boolean.
     *
     * @param permission the permission
     * @return the boolean
     */
    @TargetApi(Build.VERSION_CODES.M)
    public boolean hasPermission(String permission) {
        return Build.VERSION.SDK_INT < Build.VERSION_CODES.M ||
                checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED;
    }

    @Override
    public void onFragmentAttached() {

    }

    @Override
    public void onFragmentDetached(String tag) {

    }

    @Override
    protected void onResume() {
        super.onResume();
        checkGPSEnabled();
        startTime = System.currentTimeMillis();
        logScreenView(getScreenName());

    }

    @Override
    protected void onPause() {
        super.onPause();
        long endTime = System.currentTimeMillis();
        long duration = endTime - startTime;
        logScreenTime(getScreenName(), duration);
    }
    protected abstract String getScreenName();

    protected void logScreenView(String screenName) {
        Bundle bundle = new Bundle();
        bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, screenName);
        bundle.putString(FirebaseAnalytics.Param.SCREEN_CLASS, getClass().getSimpleName());
        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
    }
    protected void logScreenTime(String screenName, long duration) {
        Bundle bundle = new Bundle();
        bundle.putString("screen_name", screenName);
        bundle.putLong("screen_time", duration);
        mFirebaseAnalytics.logEvent("screen_time", bundle);
    }

    protected void logButtonClick(String buttonName) {
        Bundle bundle = new Bundle();
        bundle.putString("button_name", buttonName);
        mFirebaseAnalytics.logEvent("button_click", bundle);
    }

    private void checkGPSEnabled() {
        final LocationManager manager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
        if (!manager.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
            mViewModel.isGPSEnabled.postValue(false);
        } else {
            mViewModel.isGPSEnabled.postValue(true);
        }
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
//        if (hasFocus) {
////            //do anything you want here
////            Toast.makeText(this,"No",Toast.LENGTH_SHORT).show();
//            checkGPSEnabled();
//        }
        // mViewModel.isGPSEnabled.setValue(true);
        checkGPSEnabled();
    }

    @RequiresApi(api = Build.VERSION_CODES.M)
    @Override
    protected void onRestart() {
        super.onRestart();
    }


    public void hideKeyboard(Activity activity) {
        InputMethodManager imm = (InputMethodManager) activity.getSystemService(Activity.INPUT_METHOD_SERVICE);
        View view = activity.getCurrentFocus();
        if (view == null) {
            view = new View(activity);
        }
        imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
    }

    /**
     * Open activity on token expire.
     */
    public void openActivityOnTokenExpire() {
//        startActivity(LoginActivity.getStartIntent(this));
        finish();
    }

    /**
     * Is network connected boolean.
     *
     * @return the boolean
     */
    public boolean isNetworkConnected() {
        return NetworkUtils.isNetworkConnected(getApplicationContext());
    }

    /**
     * Show loading.
     */
    public void showLoading() {
        hideLoading();
        mProgressDialog = CommonUtils.showLoadingDialog(this);
        mProgressDialog.setCancelable(false);
    }

    /**
     * Hide loading.
     */
    public void hideLoading() {
        if (mProgressDialog != null && mProgressDialog.isShowing()) {
            mProgressDialog.cancel();
        }
    }

    /**
     * Gets view data binding.
     *
     * @return the view data binding
     */
    public T getViewDataBinding() {
        return mViewDataBinding;
    }

    /**
     * Override for set view model
     *
     * @return view model instance
     */
    public abstract V getViewModel();

    /**
     * Override for set binding variable
     *
     * @return variable id
     */
    public abstract int getBindingVariable();

    /**
     * Gets layout id.
     *
     * @return layout resource id
     */
    public abstract @LayoutRes
    int getLayoutId();


    /**
     * Perform dependency injection.
     */
    public void performDependencyInjection() {
        AndroidInjection.inject(this);
    }

    public void openSettingActivity() {

        Intent intent = new Intent();
        intent.setAction(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        Uri uri = Uri.fromParts("package", getPackageName(), null);
        intent.setData(uri);
        startActivity(intent);
    }

    public void showToast(String toast) {
        try {
            LayoutInflater li = getLayoutInflater();
            View layout = li.inflate(R.layout.customtoast, findViewById(R.id.custom_toast_layout));
            TextView textView = layout.findViewById(R.id.custom_toast_message);
            textView.setText(toast);

            Toast toast1 = new Toast(getApplicationContext());
            toast1.setDuration(Toast.LENGTH_SHORT);
            toast1.setGravity(Gravity.CENTER_VERTICAL, 0, 0);
            toast1.setView(layout);//setting the view of custom toast layout
            toast1.show();
        } catch (Exception e) {
            Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }
    }

    public void showSnackbar(String message) {
        Snackbar snackbar = Snackbar.make(findViewById(android.R.id.content),
                message, Snackbar.LENGTH_LONG);
        View sbView = snackbar.getView();
        sbView.setMinimumHeight(20);
        sbView.setBackgroundColor(ContextCompat.getColor(getApplicationContext(), R.color.red_ecom));
        TextView textView = sbView
                .findViewById
                        (R.id.snackbar_text);
        textView.setTextSize(12);
        textView.setTextColor(ContextCompat.getColor(this, R.color.white));

        snackbar.show();
    }


    public void showSuccessSnackbar(String message) {
        Snackbar snackbar = Snackbar.make(findViewById(android.R.id.content),
                message, Snackbar.LENGTH_LONG);
        View sbView = snackbar.getView();
        sbView.setMinimumHeight(20);
        sbView.setBackgroundColor(ContextCompat.getColor(getApplicationContext(), R.color.green));
        TextView textView = sbView
                .findViewById
                        (R.id.snackbar_text);
        textView.setTextSize(12);
        textView.setTextColor(ContextCompat.getColor(this, R.color.white));

        snackbar.show();
    }

    public boolean isInManifestGeofenceRadius(Location userLocation, double manifestLat, double manifestLong, double radiusToCheckInMeters) {
        try {
            LatLng startLatLng = new LatLng(userLocation.getLatitude(), userLocation.getLongitude());
            LatLng manifestLatLng = new LatLng(manifestLat, manifestLong);

            double distanceBetweenInMeters = SphericalUtil.computeDistanceBetween(startLatLng, manifestLatLng);
            return distanceBetweenInMeters < radiusToCheckInMeters;
        } catch (Exception e) {
            e.printStackTrace();
            //test comment
            return false;
        }
    }


    public boolean isInManifestRadiusDistanceToMethod(Location userLocation, double manifestLat, double manifestLong, double radiusToCheckInMeters) {
        if (manifestLat == 0 && manifestLong == 0) {
            return false;
        } else {
            try {
                Location manifestLocation = new Location("");
                manifestLocation.setLongitude(manifestLong);
                manifestLocation.setLatitude(manifestLat);

                double distanceBetweenInMeters = manifestLocation.distanceTo(userLocation);
                String temp = String.valueOf((int) distanceBetweenInMeters);
                //     temp = temp.split(".")[0];
                fe_distanceFromSeller = temp;
                return distanceBetweenInMeters <= radiusToCheckInMeters;
            } catch (Exception exception) {
                exception.printStackTrace();
                return false;
            }
        }

    }

    public boolean isInManifestRadiusUsingLatLng(double userLat, double userLng, double manifestLat, double manifestLong, double radiusToCheckInMeters) {
        if (manifestLat == 0 && manifestLong == 0) {
            return false;
        } else {

            Location userLocation = null;
            Location destinationLocation = null;
            try {
                userLocation = new Location("");
                destinationLocation = new Location("");

                userLocation.setLatitude(userLat);
                userLocation.setLongitude(userLng);

                destinationLocation.setLatitude(manifestLat);
                destinationLocation.setLongitude(manifestLong);

                double distanceBetweenInMeters = destinationLocation.distanceTo(userLocation);

                return distanceBetweenInMeters <= radiusToCheckInMeters;
            } catch (Exception exception) {
                exception.printStackTrace();
                return false;
            }
        }
    }

    public double getRadialDistance(Location startLocation, Location destinationLocation) {
        return startLocation.distanceTo(destinationLocation);
    }

    public double getRadialDistanceUsingLatLng(double starLat, double startLng,
                                               double destLat, double destLng) {
        if (destLat == 0 && destLng == 0) {
            return 0;
        } else {

            Location userLocation = null;
            Location destinationLocation = null;
            try {
                userLocation = new Location("");
                destinationLocation = new Location("");

                userLocation.setLatitude(starLat);
                userLocation.setLongitude(startLng);

                destinationLocation.setLatitude(destLat);
                destinationLocation.setLongitude(destLng);
            } catch (Exception e) {
                e.printStackTrace();
            }

            return ((userLocation != null) ? userLocation.distanceTo(destinationLocation) : 0);

        }
    }

    public boolean isIncorrectTimeDialogOpen = false;

    public void showIncorrectTimeAlert(String msg, boolean shouldGotoSetting) {
        isIncorrectTimeDialogOpen = true;
        AlertDialog.Builder aBuilder = new AlertDialog.Builder(this, R.style.AppCompatAlertDialogStyle);
        AlertDialog dialog = aBuilder.setTitle("Incorrect Device Time").setMessage(msg)
                .setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.dismiss();
                        isIncorrectTimeDialogOpen = false;
                        if (shouldGotoSetting) {
                            Intent intent = new Intent(Settings.ACTION_DATE_SETTINGS);
                            startActivity(intent);
                        }
                    }
                }).create();
        dialog.setCancelable(false);
        dialog.show();
    }

    public void showMultiSpaceDialog(Activity activity) {
        this.runOnUiThread(new Runnable() {
            public void run() {

                final Dialog dialog = new Dialog(activity);
                dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
                dialog.setCancelable(false);
                dialog.setCanceledOnTouchOutside(false);
                ActivityMultiSpaceBinding activityMultiSpaceBinding = DataBindingUtil.inflate(
                        LayoutInflater.from(activity),
                        R.layout.activity_multi_space,
                        (ViewGroup) mViewDataBinding.getRoot(),
                        false
                );
                dialog.setContentView(activityMultiSpaceBinding.getRoot());
                dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));

                activityMultiSpaceBinding.tvMsg.setText(R.string.multi_space);

                dialog.show();
            } /*catch (Exception e) {
                    Log.d("checkexception", String.valueOf(e));
                }*/
         });
    }
    public void showMultiSpaceDialog() {
        try{
                final Dialog dialog = new Dialog(this);
                dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
                dialog.setCancelable(false);
                dialog.setCanceledOnTouchOutside(false);
                ActivityMultiSpaceBinding activityMultiSpaceBinding = DataBindingUtil.inflate(
                        LayoutInflater.from(this),
                        R.layout.activity_multi_space,
                        (ViewGroup) mViewDataBinding.getRoot(),
                        false
                );
                dialog.setContentView(activityMultiSpaceBinding.getRoot());
                dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));

                activityMultiSpaceBinding.tvMsg.setText(R.string.multi_space);

                dialog.show();
            } catch (Exception e) {
                    Log.d("checkexception", String.valueOf(e));
                }

    }
    public static boolean checkMultiSpace(Context context, IDataManager mDataManager) {
        boolean isNotMulitSpace = false;
       if( mDataManager.getListOfMultiSpace()!= null && mDataManager.get_multiSpace_allow().equalsIgnoreCase("true")) {
           if (mDataManager.getListOfMultiSpace() != null) {
               ArrayList<String> arr_fakeApplications = mDataManager.getListOfMultiSpace();
               for (String packagename : arr_fakeApplications) {
                   boolean isPackageInstalled = CommonUtils.isPackageInstalled(packagename, context.getPackageManager());
                   if (isPackageInstalled) {
                       // Log.d("checkmulti",packagename);
                       isNotMulitSpace = true;
                       break;
                   } else {
                      // isNotMulitSpace = true;
                       isNotMulitSpace = false;

                   }
               }
           }
       }else {
           isNotMulitSpace=false;
       }
        return isNotMulitSpace;
    }


}
