package in.ecomexpress.sruti.ui.base;


import android.view.View;

import androidx.recyclerview.widget.RecyclerView;

/**
 * Generated by Dipendra on 08/11/17 - 02:10 PM
 */

public abstract class BaseViewHolder extends RecyclerView.ViewHolder {

    public BaseViewHolder(View itemView) {
        super(itemView);
    }

    public abstract void onBind(int position);

}
