package in.ecomexpress.sruti.utils.rx;

import io.reactivex.Scheduler;

/**
 * Generated by Dipendra on 07/07/17 - 12:36 PM
 */

public interface ISchedulerProvider {

    Scheduler ui();

    Scheduler computation();

    Scheduler io();

}
