package in.ecomexpress.sruti.ui.login.login;

import in.ecomexpress.sruti.model.login.LoginResponse;

import java.io.File;


/**
 * Generated by Dipendra on 13-11-2017 - 12:12 PM
 */

public interface ILoginNavigator {
    void onCallITSupportClick(String ITExecutiveNo);

    void onServerLogin();

    void onForgetPassword();

    void onSuccess();

    void onHandleError(String errorResponse);

    void openDashboardActivity();

    void showAPKForceUpdate(LoginResponse.APKUpdateResponse apkUpdateResponse);

    void showAPKSoftUpdate(LoginResponse loginResponse, LoginResponse.APKUpdateResponse apkUpdateResponse);

    void showChangePassword();

    void showVerifyOtp(boolean flag);

    void startLoginVeriyOTPActivity();

    void enableLoginButton(boolean enable);

    void showErrorMessage(boolean status);

    void noAPKUpdate();

    void showNotifyChangePasswordAlert(LoginResponse notify_password_reset_info);

    void showException(Exception e);

    void onHandleErrorAPK();

    void installAPK(File file);

    void hideProgressView();
}
