package in.ecomexpress.sruti.ui.login.login;


import androidx.lifecycle.ViewModelProvider;

import dagger.Module;
import dagger.Provides;
import in.ecomexpress.sruti.factory.ViewModelProviderFactory;
import in.ecomexpress.sruti.repo.IDataManager;
import in.ecomexpress.sruti.utils.rx.ISchedulerProvider;

/**
 * Generated by Dipendra on 13-11-2017 - 12:12 PM
 */

@Module
public class LoginActivityModule {

    @Provides
    LoginViewModel provideLoginViewModel(IDataManager dataManager,
                                         ISchedulerProvider schedulerProvider) {
        return new LoginViewModel(dataManager, schedulerProvider);
    }


    @Provides
    ViewModelProvider.Factory loginViewModelProvider(LoginViewModel loginViewModel) {
        return new ViewModelProviderFactory<>(loginViewModel);
    }

}