package in.ecomexpress.sruti.repo.local.db.prefs;


import com.google.gson.JsonObject;

import java.util.ArrayList;
import java.util.List;

import in.ecomexpress.sruti.model.DashboardBanner;
import in.ecomexpress.sruti.model.login.LoginResponse;
import in.ecomexpress.sruti.repo.IDataManager;

/**
 * Generated by Parikshit on 06-11-2017 - 10:56 AM
 */


public interface IPopPreferenceHelper {

    boolean clearPopPrefrence();
    void is_child_available(boolean is_child_available);


    boolean get_is_child_available();

    boolean get_pop_enable();

    void is_POP_Enable(boolean is_pop_enable);

}
