package in.ecomexpress.sruti.repo.local.db.prefs;


import com.google.gson.JsonObject;

import java.util.ArrayList;
import java.util.List;

import in.ecomexpress.sruti.model.DashboardBanner;
import in.ecomexpress.sruti.model.login.LoginResponse;
import in.ecomexpress.sruti.model.masterdata.application_configurations;
import in.ecomexpress.sruti.repo.IDataManager;

/**
 * Generated by Parikshit on 06-11-2017 - 10:56 AM
 */


public interface IPreferenceHelper {
    String getVehicleNo();

    void setVehicleNo(String vehicleNo);

    void setSelfVehicleType(String type);

    String getSelfVehicleType();

    void setDepartSelfVehicle(boolean departSelfVehicle);

    boolean getDepartSelfVehicle();

    String getAwbCount();

    void setAwbCount(String awbCount);

    int getCurrentUserLoggedInMode();

    void setCurrentUserLoggedInMode(IDataManager.LoggedInMode currentUserLoggedInMode);

    void setVodaOrderNo(String orderNo);


    // void setVehicleType(String vehicleType);

    // String getVehicleType();

//    void setTypeOfVehicle(String typeOfVehicle);

    void setRouteName(String routeName);

    String getMobile();

    void setMobile(String mobile);

    void setServerTime(String serverTime);
    String getServerTime();

    void updateUserLoggedInState(IDataManager.LoggedInMode loggedInMode);

    String getBottomText();

    String getCallITExecutiveNo();

    void setCallITExecutiveNo(String number);

    void setDownloadAPKIsInProcess(long b);

    long isDownloadAPKIsInProcess();

    void updateDCDetails(LoginResponse.scGeoLocation scGeoLocation);

    String getName();

    void setName(String name);

    String getAuthToken();

    void setAuthToken(String authToken);

    void isChild(boolean is_child);
  /*  void is_child_available(boolean is_child_available);*/

    void isParent(boolean isParent);

    boolean getChild();
   /* boolean get_is_child_available();*/
   /* boolean get_pop_enable();
    void is_POP_Enable(boolean is_pop_enable);
*/
    boolean getParent();

    double getCurrentLatitude();

    double getCurrentLongitude();

    void setCurrentLatitude(String latitude);
    void setCurrentLongitude(String longitude);

    String getCode();

    void setCode(String code);

    String getSOSSMSTemplate();

    String getSOSNumbers();

    boolean clearPrefrence();

    void setLocationType(Long locationType);

    void setIsUserValided(Boolean isUserValided);

    void setPhotoUrl(String photoUrl);

    void setAuthPinCode(String authPinCode);

    // long getStartTripMeterReading();
    List<LoginResponse.StartRouteDetails> getRouteDetail();

    void setRouteDetail(String routeDetails);

    void setStopTripMeterReading(long reading);


    //void setTripId(String tripId);

    //void setStartTripMeterReading(long reading);

    String getServiceCenter();

    void setServiceCenter(String serviceCenter);

    String getLocationCode();

    void setLocationCode(String locationCode);

    String getDesignation();

    void setDesignation(String designation);

    String getPstnFormat();

    void setPstnFormat(String format);

    List<DashboardBanner> getDashBoardBanner();

    void setDashBoardBanner(String dashBoardBanner);

    int getTripID();

    void setTripID(int tripID);

    void setLiveTrackingId(String live_tracking_id);

    String getLiveTrackingId();

    int getRouteID();

    void setRouteID(int routeID);

    void setCutOffTime(String time);

    String getCutOffTime();

    long getLastSyncTime();

    void setLastSyncTime(long lastSyncTime);

    boolean is_Ecom_Vehicle();

    void setecom_vehicle(boolean is_com);

    JsonObject getURL();

    void setURL(String urllist);

    void setDeparted(boolean depart);

    boolean isDepart();

    boolean isLogout();

    void setLogout(boolean logout);

    void asParentOrChild(boolean child);

    boolean getAsParentChild();

    void set_cutOffAlertTime(String config_value);

    void set_cutOffActionValue(String config_value);

    void set_live_tracking(String config_value);

    String get_live_Tracking();

    void set_erm_sync(String config_value);

    String get_erm_sync();

    void set_enable_calling(String config_value);

    String get_enable_calling();


    String get_cutOffAlertTime();

    String get_cutOffActionValue();

    void setLiveTrackingCalculatedDistance(float distance);

    float getLiveTrackingCalculatedDistance();

    void setLiveTrackingCount(int count);

    long getDistance();

    void setDistance(long distance);

    void setLiveTrackingCalculatedDistanceWithSpeed(float trackingCalculatedDistanceWithSpeed);

    int getLiveTrackingMINSpeed();

    void setLiveTrackingMINSpeed(int minSpeed);

    int getLiveTrackingSpeed();

    void setLiveTrackingSpeed(int maxSpeed);

    float getLiveTrackingCalculatedDistanceWithSpeed();

    void set_pickup_geofencing_mode(String mode);

    String get_pickup_geofencing_mode();

    void set_pickup_geofencing_radius(String radius);
    String get_pickup_geofencing_radius();

    void  set_sruti_enable_otp_for_zero_pickup(String status);
    String get_sruti_enable_otp_for_zero_pickup();

    void set_sruti_enable_delink_for_wh(String status);
    String get_sruti_enable_delink_for_wh();

    void set_sruti_allow_multispace(String status);

    String get_multiSpace_allow();

    ArrayList<String> getListOfMultiSpace();
    void setListOfMultiSpace(List<String>srutiMultiSpaceAppList);
}
